### PR TITLE
Add draft RIXS example

### PR DESCRIPTION
**Pull request by PeterC-DLS**

### CODE REVIEW

**Comment by zjttoefs** [comment]
According to travis the file does not pass the feature test.

**Comment by markbasham** [comment]
Just to clarify

```
=== examples/draft_fake_rixs.nxs ===
Entry "definition" appears to contain the following features (they validate correctly): 
	The following features failed to validate:
		NXrixs (000000005A403F80) is invalid with the following errors:
			No detectors found with any required fields
Entry "entry" appears to contain the following features (they validate correctly): 
	The following features failed to validate:
		NXrixs (000000005A403F80) is invalid with the following errors:
			No detectors found with any required fields
```

**Comment by PeterC-DLS** [comment]
Strange! I get:
```
$ python src/nxfeature.py -f 000000005A403F80 examples/draft_fake_rixs.nxs 
Entry "definition" appears to contain the following features (they validate correctly): 
	NXrixs (1514160000) {u'entry/andor': ['photoelectrons_energy', 'detector_sensitivity', 'energy_direction', 'energy_dispersion']}


Entry "entry" appears to contain the following features (they validate correctly): 
	NXrixs (1514160000) {u'entry/andor': ['photoelectrons_energy', 'detector_sensitivity', 'energy_direction', 'energy_dispersion']}

```

**Comment by markbasham** [comment]
Im getting a simmilar problem at the moment, so i will merge the request and try to fix both.

**Comment by matthew-d-jones** [comment]
I get the same result as Travis for this branch.

**Comment by markbasham** [comment]
Think its a Python3 issue, pete is investigating

**Comment by matthew-d-jones** [comment]
Yes, line 13 should be:
```python
if str(obj.attrs["NX_class"], 'utf8') in nx_class:
```

**Comment by PeterC-DLS** [comment]
Is it better to use the ```six``` package then ```six.u(obj.attrs["NX_class"])``` works in both python 2 and 3?

**Comment by matthew-d-jones** [comment]
At the meeting no one seemed to care too much about Python 2 anymore. There may be some incompatibility with exception handling for Python 2 now as well.

**Comment by PeterC-DLS** [comment]
Got a more neutral fix now

**Pull request merged**
